apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::222634367630:role/codebuild-eks-node-service-role
      username: codebuild-eks-node-service-role
      groups:
        - system:masters
  mapUsers: |
    []

