version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <ECR_REPO_URL>
  build:
    commands:
      - echo Building Docker image...
      - docker build -t <ECR_REPO_URL>:latest .
      - docker push <ECR_REPO_URL>:latest
  post_build:
    commands:
      - echo Deploying to Kubernetes...
      - kubectl apply -f k8s/
